name: Example workflow

on:
  push:
    branches:
      - main
      - cicd
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Install pmtiles'
        run: |
          pip install pmtiles
      - name: 'Convert mbtiles'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
        run: |
          aws s3api get-object --bucket $S3_BUCKET_NAME --endpoint-url S3_ENDPOINT_URL --key ABSPOA.mbtiles ABSPOA.mbtiles
          time pmtiles-convert ABSPOA.mbtiles ABSPOA.pmtiles
          ls -lah
          aws s3api put-object --bucket $S3_BUCKET_NAME --endpoint-url S3_ENDPOINT_URL --key ABSPOA.pmtiles --body ABSPOA.pmtiles
